# -*- coding: utf-8 -*-
"""FeatureEngg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PgzKXR80dsZwXyVL0PRgIE-Wj4euX2OP
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv('covid_19_clean_complete.csv')
print(df)
print(df.columns)
df_no_nan=df[df.notnull().all(axis=1)]
print(df_no_nan)
df["Recovery_rate(%)"] = (df["Recovered"]/df["Confirmed"])*100
print(df)
print(df.head)
df["total_cases"]=df['Confirmed']+df['Recovered']+df['Deaths']
print(df)
df["Active_cases"]=df['Confirmed']-df['Deaths']+df['Recovered']
print(df)
df["cases_per_100k"]=(df["Confirmed"]/df["total_cases"])*100
print(df)
import numpy as np
df["Log_Confirmed"]=np.log1p(df["Confirmed"])
print(df)
df["Risk_Score"] = (df["CFR (%)"]*0.7) + (df["cases_per_100k"]*0.3)
print(df)

df["CFR (%)"] = (df["Active"]/df["Confirmed"])*100
print(df)
print(df.head)

df["CFR (%)"] = (df["Deaths"]/df["Confirmed"])*100
print(df)
print(df.head)

bins=[0,2,5,10,100]
labels=["Low","Moderate","High","Critical"]
df["CFR_Category"] = pd.cut(df["CFR (%)"],bins=bins,labels=labels)
print(df)

bins=[0,2,5,10,100]
labels=["Low","Moderate","High","Critical"]
df["Risk_Score_Catgory"] = pd.cut(df["Risk_Score"],bins=bins,labels=labels)
print(df)
print(df.head)